[package]
name = "chat_srv"
version = "0.6.4"
edition = "2024"
authors = ["Artur Gwo≈∫dziowski"]

[dependencies]
futures-channel = "0.3.31"
futures-util = "0.3.31"
tokio = { version = "1.48.0", features = ["full"] }
tokio-tungstenite = "0.28.0"

[build-dependencies]
embed-resource = "3.0.6"