[package]
name = "ws_srv"
version = "0.4.0"
edition = "2024"
authors = ["Artur Gwo≈∫dziowski"]

[dependencies]
futures-channel = "0.3.31"
futures-util = "0.3.31"
tokio = { version = "1.46.1", features = ["full"] }
tokio-tungstenite = "0.27.0"

[build-dependencies]
embed-resource = "3.0.5"